version: "3.8"
services:
  api:
    # image: abdm6464/heyday-app:V0.0.1
    build: api 
    depends_on: 
      - postgres
    environment: 
      DB_HOST: postgres
      DB_USER: postgres
      DB_NAME: db
      DB_PASS: '0000'
      
    ports:
      - 3000:3000

# Postgres 
  postgres:
    image: postgres:10.4
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: db
    ports:
      - 35000:5432

    ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: '0000'
    ports:
      - 5050:80