apiVersion: apps/v1
kind: Deployment
metadata:
  name: heyday-api-dep 
  namespace: hey-dey-namespace
spec: 
  replicas: 1
  selector: 
    matchLabels:
        component: heyday-api
  template: 
    metadata:
      labels: 
        component: heyday-api
    spec:
      containers: 
      - name: heyday-api
        image: abdm6464/heyday-app:V0.0.2
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 3000
        env:
          - name: DB_HOST
            value: postgres-cluster-ip-service
          - name: DB_USER
            value: postgres
          - name: DB_NAME
            value: db 
          - name: DB_PASS 
            valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

--- 



apiVersion: v1
kind: Service
metadata: 
    name: heyday-svc
    namespace: hey-dey-namespace 
spec: 
  type: ClusterIP
  ports: 
    - port: 3000 #allow other pods access to this pod
      targetPort: 3000 #the target port of the containter
  selector: 
    component:  heyday-api
                 