apiVersion: apps/v1
kind: Deployment # is not perfect for stateful application 
metadata:
  name: postgres-deployment
  namespace: hey-dey-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage # storage name
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD # gettting the passord from secret 
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: POSTGRES_USER
              value: postgres
            - name : POSTGRES_DB
              value: db   
          # resources:  if you want limit the ressource used by the db 
          #   requests:
          #     memory: "50Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "500Mi"
          #     cpu: "2000m"    